name: "NowSecure Issues Test"

on:
  workflow_dispatch:
    branches: [ dev ]

jobs:
  process:
    runs-on: ubuntu-latest
    # The above stage we introduced.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: createIssues
        name: Create NowSecure issues
        uses: nowsecure/nowsecure-action/create-issues@v3
        timeout-minutes: 90
        with:
          report_id: "79f9c942-6531-11ed-8006-df7c8bd31b79"
          platform_token: ${{ secrets.NS_TOKEN }}
